[package]
name = "test-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.7.0", package = "gtk4", features = ["v4_10"] }
gio = "0.9.0"
libadwaita = "0.5.2"
adw = "0.1.0"
